# This is a basic workflow to help you get started with Actions
name: Generate Text

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron:  '0 5 * * *' 
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install GitHub CLI
        env: # Or as an environment variable
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo $RELEASE_TOKEN > token.txt
          gh auth login --with-token < token.txt

      - name: Setup Directories and Permissions
        run: |
          chmod a+x ./generate.sh
          mkdir ./releases/
        
      - name: Generate 100
        run: |
          export today=$(date +"%Y%m%d")
          ./generate.sh 100 > ./releases/random$1-${today}.txt
          
      - name: Generate 1k
        run: |
          export today=$(date +"%Y%m%d")
          ./generate.sh 1000 > ./releases/random$1-${today}.txt
          
      - name: Generate 10k
        run: |
          export today=$(date +"%Y%m%d")
          ./generate.sh 10000 > ./releases/random$1-${today}.txt
          
      - name: Generate 100k
        run: |
          export today=$(date +"%Y%m%d")
          ./generate.sh 100000 > ./releases/random$1-${today}.txt
          
      - name: Generate 1m
        run: |
          export today=$(date +"%Y%m%d")
          ./generate.sh 1000000 > ./releases/random$1-${today}.txt
          
      - name: Release Random Text
        run: |
          export today=$(date +"%Y%m%d")
          gh release create "v${today}" ./releases/*
          
        
